services:
  db:
    image: postgres:15
    container_name: my_clone_tweet_db
    environment:
      POSTGRES_DB: my_clone_tweet
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d my_clone_tweet"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: my_clone_tweet_web
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/my_clone_tweet
      - SECRET_KEY=docker-secret-key-12345
      - FLASK_DEBUG=1
    ports:
      #- "5000:5000" - раскоментировать
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./dist:/app/dist
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: my_clone_tweet_nginx
    ports:
      #- "8080:80" - раскоментировать  # Изменили порт на 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/app/uploads
      - ./dist:/app/dist
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
